### ISSUE TITLE
[GT-i8160/CM-10.1/21.09.13] Video playback & recording not working

### ISSUE THREAD

**Issue by ar-lex** [TeamCanjica/TeamCanjica#21]
Self-built CM-10.1.
[Here](https://gist.github.com/ar-lex/6653020) is the logcat fragment of starting the video playback in stock player from File Manager.
The failng libstagefright_soft_ste_aacdec.so library is in place. The file I'm trying to play was previously recorded by the stock firmware.
Video playback in YouTube app also doesn't start, thought don't give such errors.

**Comment by ar-lex** [comment]
Strangely this issue doesn't appear in official 20130925-NIGHTLY...
[This](https://gist.github.com/ar-lex/6751635) is my local manifest. What am I doing wrong?
Thanks in advance.

**Comment by RobertRozic** [comment]
I think this is fixed, i will open again if needed...

**Comment by ar-lex** [comment]
It isn't fixed for my builds yet:( Everything is OK for official builds from xda though...

I slightly changed the [local manifest](https://gist.github.com/ar-lex/6751635) for it to fit the latest changes in the team repos.

[Here](https://gist.github.com/ar-lex/7047605) is the logcat fragment from today's build. 
Now I don't have errors in STE libraries but the same fatal error in `frameworks/av/media/libstagefright/OMXCodec.cpp:1556` ([line 31 in logcat](https://gist.github.com/ar-lex/7047605#file-gt-i8160-logcat-videoplayer-error-20131018-txt-L31)) is still here.

Am I doing something wrong with the build?

Thank you very much for your hard work, guys!
